project:
  type: website

website:
  title: "Tom Saunders"
  description: "Tom Saunders' personal website."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



